### ISSUE TITLE
log库推荐

### ISSUE THREAD

**Issue by LunacyZeus** [ztino/jd_seckill#17]
log库可以考虑用glog，虽然是一个web框架的工具库，但是好像可以单独提取出来用，这个文件输出自动分割就都有了
https://itician.org/plugins/servlet/mobile?contentId=1114119#content/view/1114673

**Comment by pppscn** [comment]
不需要新增库，目前我是这样处理，同时输出到控制台和文件

`func init() {
	//将日志同时输出到控制台和文件
	file := "./" + "jd_seckill_" + time.Now().Format("20060102") + ".log"
	logFile, logErr := os.OpenFile(file, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0666)
	if logErr != nil {
		panic(logErr)
	}
	defer logFile.Close()
	mw := io.MultiWriter(os.Stdout, logFile)
	log.SetOutput(mw)
	log.SetPrefix("[jd_seckill]")
	log.SetFlags(log.LstdFlags | log.Lshortfile | log.LUTC)

	//客户端设置初始化
	common.Client = httpc.NewHttpClient()
	common.CookieJar = httpc.NewCookieJar()
	common.Client.SetCookieJar(common.CookieJar)

	//配置文件初始化
	confFile := "./conf.ini"
	var err error
	if common.Config, err = goconfig.LoadConfigFile(confFile); err != nil {
		log.Println("配置文件不存在，程序退出")
		os.Exit(0)
	}

	//抢购状态管道
	common.SeckillStatus = make(chan bool)
	log.Println("jd_seckill 程序启动成功，祝您成功！")
}`

**Comment by ztino** [comment]
> 不需要新增库，目前我是这样处理，同时输出到控制台和文件
> 
> `func init() {
> //将日志同时输出到控制台和文件
> file := "./" + "jd_seckill_" + time.Now().Format("20060102") + ".log"
> logFile, logErr := os.OpenFile(file, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0666)
> if logErr != nil {
> panic(logErr)
> }
> defer logFile.Close()
> mw := io.MultiWriter(os.Stdout, logFile)
> log.SetOutput(mw)
> log.SetPrefix("[jd_seckill]")
> log.SetFlags(log.LstdFlags | log.Lshortfile | log.LUTC)
> 
> ```
> //客户端设置初始化
> common.Client = httpc.NewHttpClient()
> common.CookieJar = httpc.NewCookieJar()
> common.Client.SetCookieJar(common.CookieJar)
> 
> //配置文件初始化
> confFile := "./conf.ini"
> var err error
> if common.Config, err = goconfig.LoadConfigFile(confFile); err != nil {
> 	log.Println("配置文件不存在，程序退出")
> 	os.Exit(0)
> }
> 
> //抢购状态管道
> common.SeckillStatus = make(chan bool)
> log.Println("jd_seckill 程序启动成功，祝您成功！")
> ```
> 
> }`
感谢

**Comment by ztino** [comment]
欢迎pr

**Comment by dandyhuang** [comment]
谁有今天的抢购日志，发出来一下
