### ISSUE TITLE
eid和fp要如何获取，能不能麻烦出一个指南？能找到的链接都404了。

### ISSUE THREAD

**Issue by losttoy** [ztino/jd_seckill#2]

**Comment by ztino** [comment]
<img width="719" alt="WX20210101-201600@2x" src="https://user-images.githubusercontent.com/76823311/103438468-53bde700-4c6e-11eb-965a-180f5585cafd.png">

**Comment by How-are-u** [comment]
## 使用教程  
#### 1. 推荐Chrome浏览器
#### 2. 网页扫码登录，或者账号密码登录
#### 3. 填写config.ini配置信息 
(1)`eid`和`fp`找个普通商品随便下单,然后抓包就能看到,这两个值可以填固定的 
> 随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台中输入变量`_JdTdudfp`，即可从输出的Json中获取`eid`和`fp`。  
> 不会的话参考原作者的issue https://github.com/zhou-xiaojun/jd_mask/issues/22

**Comment by How-are-u** [comment]
(1)`eid`和`fp`找个普通商品随便下单,然后抓包就能看到,这两个值可以填固定的 
> 随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台中输入变量`_JdTdudfp`，即可从输出的Json中获取`eid`和`fp`。  
> 不会的话参考原作者的issue https://github.com/zhou-xiaojun/jd_mask/issues/22

**Comment by How-are-u** [comment]
小白想请教一下如何运行.go   是否需要使用go get安装依赖文件

**Comment by How-are-u** [comment]
结算页面 按F12 选Console 输入_JdTdudfp 回车

**Comment by ruixule** [comment]
> 小白想请教一下如何运行.go 是否需要使用go get安装依赖文件

肯定需要的的 我的微信1414100586

**Comment by ruixule** [comment]
解决了吗 没有的话 我远程看下

**Comment by losttoy** [comment]
我的是MAC+CHROME，可以找到eid（在response），不能找到fp，是不是版本有差异的？

**Comment by theWangRichard** [comment]
请问抢购链接获取失败是怎么回事
