### ISSUE TITLE
大佬，抢购失败，直接报数组越界了。

### ISSUE THREAD

**Issue by kugooer** [ztino/jd_seckill#20]
2021/01/05 10:01:02 访问商品的抢购连接...
2021/01/05 10:01:02 访问抢购订单结算页面...
2021/01/05 10:01:02 访问抢购订单结算页面...
2021/01/05 10:01:02 获取秒杀初始化信息...
2021/01/05 10:01:02 获取秒杀初始化信息...
panic: runtime error: index out of range [0] with length 0

goroutine 66 [running]:
github.com/ztino/jd_seckill/jd_seckill.(*Seckill).SubmitSeckillOrder(0xc00028e660, 0x0)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/jd_seckill/seckill.go:185 +0x3f2a
github.com/ztino/jd_seckill/cmd.task(0xc00028e660)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:99 +0x53
created by github.com/ztino/jd_seckill/cmd.Start
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:88 +0x228

**Comment by zwf8558** [comment]
2021/01/05 10:00:01 抢购链接获取成功:https://marathon.jd.com/captcha.html?skuId=100012043978&sn=c73896a953dce3c00efa854f43e20df4&from=pc
2021/01/05 10:00:01 访问商品的抢购连接...
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 用户:front88
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 用户:front88
2021/01/05 10:00:01 用户:front88
2021/01/05 10:00:01 返回信息:jQuery5240470({"type":"3","state":"12","st":1609812000,"en":1609813800,"url":"//divide.jd.com/user_routing?skuId=100012043978&sn=c73896a953dce3c00efa854f43e20df4&from=pc"})

2021/01/05 10:00:01 抢购链接获取成功:https://marathon.jd.com/captcha.html?skuId=100012043978&sn=c73896a953dce3c00efa854f43e20df4&from=pc
2021/01/05 10:00:01 访问商品的抢购连接...
2021/01/05 10:00:01 获取秒杀初始化信息...
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 获取秒杀初始化信息...
2021/01/05 10:00:01 商品名称:飞天 53%vol  500ml 贵州茅台酒（带杯）
2021/01/05 10:00:01 商品名称:飞天 53%vol  500ml 贵州茅台酒（带杯）
panic: runtime error: index out of range [0] with length 0

goroutine 31 [running]:
github.com/ztino/jd_seckill/jd_seckill.(*Seckill).SubmitSeckillOrder(0x11cd52e8, 0x0)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/jd_seckill/seckill.go:185 +0x2f91
github.com/ztino/jd_seckill/cmd.task(0x11cd52e8)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:99 +0x39
created by github.com/ztino/jd_seckill/cmd.Start
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:88 +0x23c

**Comment by hanluner** [comment]
debug了一下，是 SeckillInitInfo信息根本没获取到。

**Comment by ztino** [comment]
已经定位问题了，判断没写好，可能是个json，但是不会返回地址等信息，等我晚上修复，在我看来这是一个好消息。

**Comment by ztino** [comment]
说明脚本可用，还需要大家一起调试，有谁能提供一下，现在获取不到addressList的返回json

**Comment by hanluner** [comment]
> 已经定位问题了，判断没写好，可能是个json，但是不会返回地址等信息，等我晚上修复，在我看来这是一个好消息。

但是看下面提交订单的逻辑，这个地址是必需字段。

**Comment by ztino** [comment]
可以在SeckillInitInfo循环获取，获取到跳出，或者等待1.5秒发起下一波任务

**Comment by scemsjyd** [comment]
![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
返回的是null

**Comment by kugooer** [comment]
> 说明脚本可用，还需要大家一起调试，有谁能提供一下，现在获取不到addressList的返回json

2021/01/05 10:00:00 商品名称:飞天 53%vol  500ml 贵州茅台酒（带杯）
2021/01/05 10:00:00 商品名称:飞天 53%vol  500ml 贵州茅台酒（带杯）
2021/01/05 10:00:00 返回信息:jQuery4079951({"type":"3","state":"13","url":""})

2021/01/05 10:00:00 抢购链接获取失败，稍后自动重试
2021/01/05 10:00:00 返回信息:jQuery1551304({"type":"3","state":"13","url":""})

2021/01/05 10:00:00 抢购链接获取失败，稍后自动重试
2021/01/05 10:00:01 返回信息:jQuery6031760({"type":"3","state":"12","st":1609812000,"en":**********,"url":"//divide.jd.com/user_routing?skuId=100012043978&sn=*******************************&from=pc"})

2021/01/05 10:00:01 抢购链接获取成功:https://marathon.jd.com/captcha.html?skuId=100012043978&sn=*******************************&from=pc
2021/01/05 10:00:01 访问商品的抢购连接...
2021/01/05 10:00:01 返回信息:jQuery6401799({"type":"3","state":"12","st":1609812000,"en":**********,"url":"//divide.jd.com/user_routing?skuId=100012043978&sn=*******************************&from=pc"})

2021/01/05 10:00:01 抢购链接获取成功:https://marathon.jd.com/captcha.html?skuId=100012043978&sn=*******************************&from=pc
2021/01/05 10:00:01 访问商品的抢购连接...
2021/01/05 10:00:01 返回信息:jQuery1551304({"type":"3","state":"12","st":1609812000,"en":**********,"url":"//divide.jd.com/user_routing?skuId=100012043978&sn=*******************************&from=pc"})

2021/01/05 10:00:01 抢购链接获取成功:https://marathon.jd.com/captcha.html?skuId=100012043978&sn=*******************************&from=pc
2021/01/05 10:00:01 访问商品的抢购连接...
2021/01/05 10:00:01 访问抢购订单结算页面...
2021/01/05 10:00:01 获取秒杀初始化信息...
2021/01/05 10:00:02 用户:******
2021/01/05 10:00:02 用户:******
panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
github.com/ztino/jd_seckill/jd_seckill.(*Seckill).SubmitSeckillOrder(0xc000071810, 0x0)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/jd_seckill/seckill.go:185 +0x3f2a
github.com/ztino/jd_seckill/cmd.task(0xc000071810)
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:99 +0x53
created by github.com/ztino/jd_seckill/cmd.Start
        /Users/albertzhan/GoProject/mygo/src/github.com/ztino/jd_seckill/cmd/seckill.go:88 +0x228

**Comment by ztino** [comment]
> ![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
> 返回的是null
感谢

**Comment by dandyhuang** [comment]
今天没来的急验证，默认地址kugooer你是不是没有填，没买过东西

**Comment by dandyhuang** [comment]
> > ![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
> > 返回的是null
> > 感谢

这个测试是怎么测试的

**Comment by ztino** [comment]
> 今天没来的急验证，默认地址kugooer你是不是没有填，没买过东西

链接获取失败已经解决了，问题出在重定向上

**Comment by ztino** [comment]
> > > ![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
> 
> > > 返回的是null
> 
> > > 感谢
> 
> 
> 
> 这个测试是怎么测试的

测试初始化信息可以这么干，登录流程走完，直接调用获取初始化信息的方法，正常时段都是一个正常的json，但是抢购时会返回null的字符串，关键让我郁闷的是gjson居然检测是一个json😅

**Comment by dandyhuang** [comment]
> > > > ![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
> > 
> > 
> > > > 返回的是null
> > 
> > 
> > > > 感谢
> > 
> > 
> > 这个测试是怎么测试的
> 
> 测试初始化信息可以这么干，登录流程走完，直接调用获取初始化信息的方法，正常时段都是一个正常的json，但是抢购时会返回null的字符串，关键让我郁闷的是gjson居然检测是一个json😅

https://blog.csdn.net/torresaaa/article/details/104850356
![image](https://user-images.githubusercontent.com/12603054/103607796-bce67880-4f54-11eb-8c0b-556f2632bcaf.png)
看了下其他秒杀，也是这个逻辑，但是很奇怪，为什么，这个获取的是null字符串

**Comment by scemsjyd** [comment]
```
func task(seckill *jd_seckill.Seckill)  {
	seckill.RequestSeckillUrl()
	seckill.SeckillPage()
	flag:=seckill.SubmitSeckillOrder()
	//提前抢购成功的,直接结束程序
	if flag {
		//通知管道
		common.SeckillStatus<-true
	}
}
```

这里有个问题，如果这个任务像上面的提交秒杀失败，就会结束，总会开启了5个goroutine，都会失败。是否可以判断如果失败就循环重试。像python中写的那样抓到异常重试，直到成功

https://github.com/ChinaVolvocars/jd_maotai_seckill/blob/master/maotai/jd_spider_requests.py#L498:9

```
def _seckill(self):
        """
        抢购
        """
        while True:
            try:
                self.request_seckill_url()
                while True:
                    self.request_seckill_checkout_page()
                    self.submit_seckill_order()
            except Exception as e:
                logger.info('抢购发生异常，稍后继续执行！', e)
            wait_some_time()
```

**Comment by ztino** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
> > > 
> > > 
> > > > > 返回的是null
> > > 
> > > 
> > > > > 感谢
> > > 
> > > 
> > > 这个测试是怎么测试的
> > 
> > 
> > 测试初始化信息可以这么干，登录流程走完，直接调用获取初始化信息的方法，正常时段都是一个正常的json，但是抢购时会返回null的字符串，关键让我郁闷的是gjson居然检测是一个json😅
> 
> https://blog.csdn.net/torresaaa/article/details/104850356
> ![image](https://user-images.githubusercontent.com/12603054/103607796-bce67880-4f54-11eb-8c0b-556f2632bcaf.png)
> 看了下其他秒杀，也是这个逻辑，但是很奇怪，为什么，这个获取的是null字符串

我比较好奇gjson是怎么把一个null字符串判断为是一个合格的json，你可以测试下

**Comment by scemsjyd** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/14870062/103598989-fe6c2900-4f3e-11eb-9329-1e49d9a60472.png)
> > > > 
> > > > 
> > > > > > 返回的是null
> > > > 
> > > > 
> > > > > > 感谢
> > > > 
> > > > 
> > > > 这个测试是怎么测试的
> > > 
> > > 
> > > 测试初始化信息可以这么干，登录流程走完，直接调用获取初始化信息的方法，正常时段都是一个正常的json，但是抢购时会返回null的字符串，关键让我郁闷的是gjson居然检测是一个json😅
> > 
> > 
> > https://blog.csdn.net/torresaaa/article/details/104850356
> > ![image](https://user-images.githubusercontent.com/12603054/103607796-bce67880-4f54-11eb-8c0b-556f2632bcaf.png)
> > 看了下其他秒杀，也是这个逻辑，但是很奇怪，为什么，这个获取的是null字符串
> 
> 我比较好奇gjson是怎么把一个null字符串判断为是一个合格的json，你可以测试下

我看了一下gjson的源码，gjson.Valid()方法中调用了下面这个方法判断

```
func validany(data []byte, i int) (outi int, ok bool) {
	for ; i < len(data); i++ {
		switch data[i] {
		default:
			return i, false
		case ' ', '\t', '\n', '\r':
			continue
		case '{':
			return validobject(data, i+1)
		case '[':
			return validarray(data, i+1)
		case '"':
			return validstring(data, i+1)
		case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			return validnumber(data, i+1)
		case 't':
			return validtrue(data, i+1)
		case 'f':
			return validfalse(data, i+1)
		case 'n':
			return validnull(data, i+1)
		}
	}
	return i, false
}
```
null返回了true

**Comment by dandyhuang** [comment]
> ```
> func task(seckill *jd_seckill.Seckill)  {
> 	seckill.RequestSeckillUrl()
> 	seckill.SeckillPage()
> 	flag:=seckill.SubmitSeckillOrder()
> 	//提前抢购成功的,直接结束程序
> 	if flag {
> 		//通知管道
> 		common.SeckillStatus<-true
> 	}
> }
> ```
> 
> 这里有个问题，如果这个任务像上面的提交秒杀失败，就会结束，总会开启了5个goroutine，都会失败。是否可以判断如果失败就循环重试。像python中写的那样抓到异常重试，直到成功
> 
> https://github.com/ChinaVolvocars/jd_maotai_seckill/blob/master/maotai/jd_spider_requests.py#L498:9
> 
> ```
> def _seckill(self):
>         """
>         抢购
>         """
>         while True:
>             try:
>                 self.request_seckill_url()
>                 while True:
>                     self.request_seckill_checkout_page()
>                     self.submit_seckill_order()
>             except Exception as e:
>                 logger.info('抢购发生异常，稍后继续执行！', e)
>             wait_some_time()
> ```

我觉得可以加个recover试试。后面来验证一下

**Comment by kugooer** [comment]
> 没来的急验证，默认地址kugooer你是不是没有填，没买过东西

去年一年都在京东上面买的东西。 默认地址也有

**Comment by hanluner** [comment]
有人知道有哪个解决方案，提个方案出来改，或者作者已经知道了思路吗？

**Comment by ztino** [comment]
> 有人知道有哪个解决方案，提个方案出来改，或者作者已经知道了思路吗？

已经有解决方案了，晚上晚点出解决方案吧，现在有方案的也可以提交pr

**Comment by hanluner** [comment]
> > 有人知道有哪个解决方案，提个方案出来改，或者作者已经知道了思路吗？
> 
> 已经有解决方案了，晚上晚点出解决方案吧，现在有方案的也可以提交pr

需要帮忙写代码的地方，可以提一下，大家一起帮忙。

**Comment by dandyhuang** [comment]
我提交吧，这个还是很容易的

**Comment by ztino** [comment]
已解决
