### ISSUE TITLE
WIN7的EXE咋运行啊？

### ISSUE THREAD

**Issue by wdwwwbw** [ztino/jd_seckill#22]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\Desktop\conf.ini

C:\Users\Administrator>C:\Users\Administrator\Desktop\jd_seckill.exe
2021/01/05 11:30:47 配置文件不存在，程序退出

C:\Users\Administrator>
直接点EXE文件让我去CMD里运行，但是提示上面的东西

**Comment by wdwwwbw** [comment]
Thisis acommandline too l-
ou need to open cnd.exe and run it from ther

**Comment by ztino** [comment]
仓库描述文件上有写具体如何使用，请注意查看，如感觉描述文件生涩，欢迎pr

**Comment by gaolengdexiaoming** [comment]
> Microsoft Windows [版本 6.1.7601]
> 版权所有 (c) 2009 Microsoft Corporation。保留所有权利。
> 
> C:\Users\Administrator>C:\Users\Administrator\Desktop\conf.ini
> 
> C:\Users\Administrator>C:\Users\Administrator\Desktop\jd_seckill.exe
> 2021/01/05 11:30:47 配置文件不存在，程序退出
> 
> C:\Users\Administrator>
> 直接点EXE文件让我去CMD里运行，但是提示上面的东西

cmd 
cd C:\Users\Administrator\Desktop\jd_seckill
jd_seckill login
然后文件夹下面会生成一个二维码 打开京东APP 扫描 登录即可

**Comment by wdwwwbw** [comment]
> > Microsoft Windows [版本6.1.7601]
> > 版权所有（c）2009 Microsoft Corporation。保留所有权利。
> > C：\ Users \ Administrator> C：\ Users \ Administrator \ Desktop \ conf.ini
> > C：\ Users \ Administrator> C：\ Users \ Administrator \ Desktop \ jd_seckill.exe 
> > 2021/01/05 11:30:47配置文件不存在，程序退出
> > C：\ Users \ Administrator>直接
> > 点EXE文件让我去CMD里运行，但是提示上面的东西
> 
> cmd 
> cd C：\ Users \ Administrator \ Desktop \ jd_seckill 
> jd_seckill登录
> 然后文件夹下面的会生成一个二维码：京东APP扫描登录即可

配置文件不存在，程序退出，我再研究研究吧..
