### ISSUE TITLE
请问抢购时间设置支持毫秒吗？

### ISSUE THREAD

**Issue by flyhong666** [ztino/jd_seckill#28]
抢购时间设置为： 2021-01-06 09:59:59.700 这样可以吗？如果要设置毫秒是不是这样输入呢？

**Comment by ztino** [comment]
暂时不支持，但是使用上没有影响

**Comment by flyhong666** [comment]
> 暂时不支持，但是使用上没有影响

大佬，能不能再完善一下，让其支持毫秒呢。
