### ISSUE TITLE
获取秒杀初始化信息失败,返回信息:null,这是什么原因

### ISSUE THREAD

**Issue by samGly** [ztino/jd_seckill#29]
访问商品的抢购连接...
[jd_seckill] 2021/01/06 02:02:09 seckill.go:124: 访问抢购订单结算页面...
[jd_seckill] 2021/01/06 02:02:09 seckill.go:124: 访问抢购订单结算页面...
[jd_seckill] 2021/01/06 02:02:09 seckill.go:159: 获取秒杀初始化信息失败,返回信息:null
[jd_seckill] 2021/01/06 02:02:09 seckill.go:124: 访问抢购订单结算页面...
[jd_seckill] 2021/01/06 02:02:09 seckill.go:159: 获取秒杀初始化信息失败,返回信息:null
[jd_seckill] 2021/01/06 02:02:09 seckill.go:176: 抢购失败，无法获取生成订单的基本信息，接口返回:【null】
[jd_seckill] 2021/01/06 02:02:09 seckill.go:176: 抢购失败，无法获取生成订单的基本信息，接口返回:【null】
[jd_seckill] 2021/01/06 02:02:09 seckill.go:140: 获取秒杀初始化信息...
[jd_seckill] 2021/01/06 02:02:10 seckill.go:140: 获取秒杀初始化信息...
[jd_seckill] 2021/01/06 02:02:10 seckill.go:140: 获取秒杀初始化信息...
[jd_seckill] 2021/01/06 02:02:10 seckill.go:101: 用户:xxx
[jd_seckill] 2021/01/06 02:02:10 seckill.go:159: 获取秒杀初始化信息失败,返回信息:null
[jd_seckill] 2021/01/06 02:02:10 seckill.go:159: 获取秒杀初始化信息失败,返回信息:null

**Comment by ztino** [comment]
正常现象

**Comment by ztino** [comment]
我这边的建议是，只要不是抢购成功，就保持每天运行脚本，能抢到就抢到，不能抢到就随缘，让我们站在黄牛同一起跑线上

**Comment by ztino** [comment]
如果怕封号，请修改配置文件里的参数，降低频率

**Comment by dandyhuang** [comment]
> 好的哥，返回码不是90008是不就是能抢只不过没抢到

风控了。大哥你这个

**Comment by samGly** [comment]
> > 好的哥，返回码不是90008是不就是能抢只不过没抢到
> 
> 风控了。大哥你这个


> > 好的哥，返回码不是90008是不就是能抢只不过没抢到
> 
> 风控了。大哥你这个

我返回码是90016不是90008，没有被风控吧
