### ISSUE TITLE
你们这个读取这个配置文件的 参数都不对呀 为什么要加===============

### ISSUE THREAD

**Issue by ruixule** [ztino/jd_seckill#3]
![image](https://user-images.githubusercontent.com/33270841/103441049-17968080-4c86-11eb-87cb-ce90299ddada.png)

你们这个读取这个配置文件的 参数都不对呀 为什么要加===============

**Comment by ztino** [comment]
做分割符号用的，后续会替换配置读取库的

**Comment by ruixule** [comment]
> 做分割符号用的，后续会替换配置读取库的

如果我吧这个 ========= 替换成 . 没有问题吧，请问作者你使用的 go 版本多少，
为什么没有使用go mod 这样更方便大家 下包的，
没有日志输出，我已经本地添加了
如果方便的话我 想参与该项目，

**Comment by ztino** [comment]
> > 做分割符号用的，后续会替换配置读取库的
> 
> 
> 
> 如果我吧这个 ========= 替换成 . 没有问题吧，请问作者你使用的 go 版本多少，
> 
> 为什么没有使用go mod 这样更方便大家 下包的，
> 
> 没有日志输出，我已经本地添加了
> 
> 如果方便的话我 想参与该项目，

替换成.没问题的，后续打算更换go mod了，目前日志没有写入到文件，由于时间仓促这些没加上，但是都在安排之内，欢迎pr
