### ISSUE TITLE
一直提示“无法获取生成订单的基本信息“，不知道是怎么个情况

### ISSUE THREAD

**Issue by hyperbo** [ztino/jd_seckill#30]
![image](https://user-images.githubusercontent.com/27429328/103720575-a00a7d80-5006-11eb-92fc-0d791b1a8b44.png)

**Comment by ztino** [comment]
正常现象

**Comment by flyhong666** [comment]
大哥，你的怎么是2点？在国外？

**Comment by ztino** [comment]
> 大哥，你的怎么是2点？在国外？

日志时间错误问题，最新版本才会
