### ISSUE TITLE
目前需要优化的功能还是日志

### ISSUE THREAD

**Issue by ztino** [ztino/jd_seckill#33]
采用目前的日志方案:
1.需要修改UTC时间
2.看是否能够解决log.println不能写入日志文件的问题
修改目前日志方案，可直接pr，这里面可能有我很大问题，因为一开始赶在周一前发布，日志功能没有考虑这么全面，所以现在可能需要改动挺多地方的

**Comment by pppscn** [comment]
1、不是问题：log.SetFlags(log.LstdFlags | log.Lshortfile | log.Lmicroseconds)

2、log.Println也能写入，只是每次 import "log"都要一次 log.SetOutput(logFile)

我等下整理一下提pr吧，只是我用goland习惯性格式化代码，每次整合代码都要手动跟你的比对一下，有点懒

**Comment by pppscn** [comment]
重写log标准库，将日志同时输出到控制台和文件
https://github.com/ztino/jd_seckill/pull/35
