### ISSUE TITLE
import 导入文件语法问题

### ISSUE THREAD

**Issue by yzhack** [ztino/jd_seckill#4]
切换成了go modules
import (
	"errors"
	"fmt"
	"github.com/Albert-Zhan/httpc"
	"github.com/tidwall/gjson"
	"jd_seckill/common"
	"jd_seckill/conf"
	"jd_seckill/jd_seckill"
	"log"
	"net/http"
	"os"
	"runtime"
	"sync"
	"time"
)
配置文件库操作推荐使用 viper 这个配置文件用库，语法简单，配置简单

**Comment by ztino** [comment]
多谢指点，不是专业goer，所以有改进的地方请指点，后续替换吧，感谢建议，写着仓促所以没考虑这么多，欢迎pr

**Comment by ztino** [comment]
以使用go mod，ini配置文件读取以替换goconfig
