### ISSUE TITLE
扫描二维码登录后，程序闪退

### ISSUE THREAD

**Issue by lenngennd** [ztino/jd_seckill#5]
扫描二维码登录后，程序闪退

**Comment by ztino** [comment]
请提供报错信息，我本地未发现

**Comment by lenngennd** [comment]
哪里能看到报错信息，就是登录后一闪而过，然后主程序自动关闭
eid = fp = 用不用加“”

**Comment by iinine** [comment]
> 哪里能看到报错信息，就是登录后一闪而过，然后主程序自动关闭
> eid = fp = 用不用加“”

还是老老实实的搭建go环境吧，搭建了都正常了，还有有可能是你的定时值没修改

**Comment by lenngennd** [comment]
果然是定时值的问题 改了就正常了~~~
