### ISSUE TITLE
抢购链接获取失败

### ISSUE THREAD

**Issue by Xuzan9396** [ztino/jd_seckill#6]
![image](https://user-images.githubusercontent.com/24741439/103471377-9e4c7a00-4dba-11eb-9957-5e6753ef301c.png)

**Comment by Xuzan9396** [comment]
只能抢茅台吗

**Comment by Xuzan9396** [comment]
@ztino

**Comment by ztino** [comment]
是的

**Comment by nvren552** [comment]
能加个联系方式吗 Q1263652853
