### ISSUE TITLE
cookie.txt文件没有生成

### ISSUE THREAD

**Issue by LockiJiang** [ztino/jd_seckill#7]
cookie.txt文件没有生成

**Comment by ztino** [comment]
那应该有错误信息吧

**Comment by ztino** [comment]
mac和windows测试过没有问题，具体请提供复现步骤和错误信息

**Comment by jhcrony** [comment]
扫码不弹出二维码，但是会下载二维码，要自己打开二维码文件扫描，扫描登陆后不会生成cookie，但是中途无错误。

**Comment by LockiJiang** [comment]
> 
> 
> mac和windows测试过没有问题，具体请提供复现步骤和错误信息

 @jhcrony 的描述和我一致，win10 19042，命令行下执行exe运行，运行一切正常，没有报错，登录不弹出二维码，运行后不生成cookie文件，运行完也没有日志文件

**Comment by ztino** [comment]
0.1.6才有cookie.txt文件的，不弹出二维码是这边系统匹配问题，没有找到相关命令调用打开二维码，请手动打开扫描
