### ISSUE TITLE
获取eid和fp，浏览器卡住不动

### ISSUE THREAD

**Issue by wupyweb** [ztino/jd_seckill#8]

**Comment by ztino** [comment]
在我本地开发中有偶现过，具体原因还在测试调试中，解决方法：请结束程序，多重试几次，目前在安装了chrome的windows10和mac上测试使用没啥问题

**Comment by bbhsky** [comment]
我也有这个情况
Mac
2021/01/04 10:21:59 加载cookie成功
2021/01/04 10:22:00 开始自动获取eid和fp，如遇卡住请结束进程，重新启动
2021/01/04 10:22:07 ERROR: received DOM.documentUpdated when there's no top-level frame

go version go1.15.6 darwin/amd64

**Comment by ztino** [comment]
> 我也有这个情况
> Mac
> 2021/01/04 10:21:59 加载cookie成功
> 2021/01/04 10:22:00 开始自动获取eid和fp，如遇卡住请结束进程，重新启动
> 2021/01/04 10:22:07 ERROR: received DOM.documentUpdated when there's no top-level frame
> 
> go version go1.15.6 darwin/amd64

这种结束进程，多重试几次就好了

**Comment by beyond510** [comment]
我这边是这样的：

首先运行login，扫码成功，获取COOKIE成功。
然后运行jdTdudfp
CMD显示：

C:\****>jd_seckill jdTdudfp
2021/01/04 11:13:04 加载cookie成功
2021/01/04 11:13:04 开始自动获取eid和fp，如遇卡住请结束进程，重新启动
（然后就没有别的了）

自动弹出了chrome，先打开了jd.com并自动根据cookie登录了，然后访问了https://jiadian.jd.com/
然后。。。。就不动了。。。就没有然后了。。。

试了若干次都是这样，系统是WIN10 64位专业版，CHROME是刚从官网下载的最新版并默认安装的。

**Comment by ztino** [comment]
目前有比较完美的解决方案就是调整使用方式，一来也解决随机访问商品链接，访问到不能加入购物车的商品，二来也解决频繁卡住的问题。
晚上有空出个dome吧，使用方式：
jd_seckill jdTdudfp -good_url 商品链接

**Comment by pppscn** [comment]
> 目前有比较完美的解决方案就是调整使用方式，一来也解决随机访问商品链接，访问到不能加入购物车的商品，二来也解决频繁卡住的问题。
> 晚上有空出个dome吧，使用方式：
> jd_seckill jdTdudfp -good_url 商品链接

直接把测试商品的sku_id写在conf.ini 更好一些

**Comment by ztino** [comment]
> > 目前有比较完美的解决方案就是调整使用方式，一来也解决随机访问商品链接，访问到不能加入购物车的商品，二来也解决频繁卡住的问题。
> 
> > 晚上有空出个dome吧，使用方式：
> 
> > jd_seckill jdTdudfp -good_url 商品链接
> 
> 
> 
> 直接把测试商品的sku_id写在conf.ini 更好一些

目前阶段是打算做成工具使用的，所以我感觉是用参数会比较好点，conf.ini就放抢购的一些配置吧

**Comment by pppscn** [comment]
**已经优化自动获取eid和fp，并写入conf.ini**

https://github.com/pppscn/jd_seckill/commit/9c04975e62d536491a2366fdf62feb92454325c3

可能不符合z大的规划，就不提pr了，其他兄弟可以参考一下

**Comment by ztino** [comment]
> **已经优化自动获取eid和fp，并写入conf.ini**
> 
> [pppscn@9c04975](https://github.com/pppscn/jd_seckill/commit/9c04975e62d536491a2366fdf62feb92454325c3)
> 
> 可能不符合z大的规划，就不提pr了，其他兄弟可以参考一下

为什么目前阶段不考虑写入配置文件和商品链接配置化，那是因为我发现chromedp并不是很稳定，可能我还未完全掌握使用，还有一个就是跨平台的考虑，服务器是需要安装headless-chrome的，所以这也是我为什么要把自动获取的抢分一个命令使用，待稳定后会考虑写入配置文件

**Comment by pppscn** [comment]
> > **已经优化自动获取eid和fp，并写入conf.ini**
> > [pppscn@9c04975](https://github.com/pppscn/jd_seckill/commit/9c04975e62d536491a2366fdf62feb92454325c3)
> > 可能不符合z大的规划，就不提pr了，其他兄弟可以参考一下
> 
> 为什么目前阶段不考虑写入配置文件和商品链接配置化，那是因为我发现chromedp并不是很稳定，可能我还未完全掌握使用，还有一个就是跨平台的考虑，服务器是需要安装headless-chrome的，所以这也是我为什么要把自动获取的抢分一个命令使用，待稳定后会考虑写入配置文件

优化后，基本上一次获取成功，如果失败自动重试5次（可配置）
