### ISSUE TITLE
希望可以加入秒杀其他商品的功能

### ISSUE THREAD

**Issue by zhlkoa556** [ztino/jd_seckill#9]

**Comment by ztino** [comment]
暂时不考虑，一个人维护成本太高了，等待其他大佬加入吧，目前会把精力放在茅台抢购上

**Comment by kugooer** [comment]
> 暂时不考虑，一个人维护成本太高了，等待其他大佬加入吧，目前会把精力放在茅台抢购上

大佬，加油！ 等你的版本抢茅台了

**Comment by dandyhuang** [comment]
有其他需求的，可以提一下，@ztino我可以帮忙支持一下

**Comment by ztino** [comment]
> 有其他需求的，可以提一下，@ztino我可以帮忙支持一下

感谢大佬，有时间可以研究优化下下载二维码后，调用程序打开的适配，主要还是windows 目前我发现windows10是无法打开的。https://github.com/ztino/jd_seckill/blob/main/common/lib.go#L98
还有docker镜像的支持

**Comment by dandyhuang** [comment]
> > 有其他需求的，可以提一下，@ztino我可以帮忙支持一下
> 
> 感谢大佬，有时间可以研究优化下下载二维码后，调用程序打开的适配，主要还是windows 目前我发现windows10是无法打开的。https://github.com/ztino/jd_seckill/blob/main/common/lib.go#L98
> 还有docker镜像的支持

可以

**Comment by pppscn** [comment]
> > 有其他需求的，可以提一下，@ztino我可以帮忙支持一下
> 
> 感谢大佬，有时间可以研究优化下下载二维码后，调用程序打开的适配，主要还是windows 目前我发现windows10是无法打开的。https://github.com/ztino/jd_seckill/blob/main/common/lib.go#L98
> 还有docker镜像的支持

windows 10 我调用照片查看器打开图片没问题，z大参考一下

Windows系统调用照片查看器显示二维码；非WIN系统输出控制台
https://github.com/pppscn/jd_seckill/commit/a17cb986277995afdf2ef87d3e21fb42bf57d250

**Comment by ztino** [comment]
> > > 有其他需求的，可以提一下，@ztino我可以帮忙支持一下
> > 
> > 
> > 感谢大佬，有时间可以研究优化下下载二维码后，调用程序打开的适配，主要还是windows 目前我发现windows10是无法打开的。https://github.com/ztino/jd_seckill/blob/main/common/lib.go#L98
> > 还有docker镜像的支持
> 
> windows 10 我调用照片查看器打开图片没问题，z大参考一下
> 
> Windows系统调用照片查看器显示二维码；非WIN系统输出控制台
> [pppscn@a17cb98](https://github.com/pppscn/jd_seckill/commit/a17cb986277995afdf2ef87d3e21fb42bf57d250)

大佬建议整理下写在common.OpenImage里，mac那个可以保留，Windows就用你这个，其余系统输出控制台，给我提交个pr吧

**Comment by ztino** [comment]
> > > 有其他需求的，可以提一下，@ztino我可以帮忙支持一下
> > 
> > 
> > 感谢大佬，有时间可以研究优化下下载二维码后，调用程序打开的适配，主要还是windows 目前我发现windows10是无法打开的。https://github.com/ztino/jd_seckill/blob/main/common/lib.go#L98
> > 还有docker镜像的支持
> 
> windows 10 我调用照片查看器打开图片没问题，z大参考一下
> 
> Windows系统调用照片查看器显示二维码；非WIN系统输出控制台
> [pppscn@a17cb98](https://github.com/pppscn/jd_seckill/commit/a17cb986277995afdf2ef87d3e21fb42bf57d250)

看你fork改的很不错，给你点赞了，可以提交pr，我省得去你那拉

**Comment by dandyhuang** [comment]
> > > 有其他需求的，可以提一下，@ztino我可以帮忙支持一下
> > 
> > 
> > 感谢大佬，有时间可以研究优化下下载二维码后，调用程序打开的适配，主要还是windows 目前我发现windows10是无法打开的。https://github.com/ztino/jd_seckill/blob/main/common/lib.go#L98
> > 还有docker镜像的支持
> 
> windows 10 我调用照片查看器打开图片没问题，z大参考一下
> 
> Windows系统调用照片查看器显示二维码；非WIN系统输出控制台
> [pppscn@a17cb98](https://github.com/pppscn/jd_seckill/commit/a17cb986277995afdf2ef87d3e21fb42bf57d250)

越来越多大佬一起共建了😄

**Comment by ztino** [comment]
等这些问题解决优化完，我打算把精力放在自动获取下一次抢购时间上，实现自动抢购，最近测试京东登陆cookie会话，有效时间挺长的，还是可以做长时间运行的。

**Comment by dandyhuang** [comment]
> 等这些问题解决优化完，我打算把精力放在自动获取下一次抢购时间上，实现自动抢购，最近测试京东登陆cookie会话，有效时间挺长的，还是可以做长时间运行的。

cookie时间可以续期的，应该有接口，这种都可以慢慢优化，先把功能走通把

**Comment by ztino** [comment]
> > 等这些问题解决优化完，我打算把精力放在自动获取下一次抢购时间上，实现自动抢购，最近测试京东登陆cookie会话，有效时间挺长的，还是可以做长时间运行的。
> 
> 
> 
> cookie时间可以续期的，应该有接口，这种都可以慢慢优化，先把功能走通把

续期活跃的已经都有了，先把这些bug跟功能优化了，后面能自动抢购的话，docker镜像还是很有用的，服务器部署

**Comment by dandyhuang** [comment]
> > > 等这些问题解决优化完，我打算把精力放在自动获取下一次抢购时间上，实现自动抢购，最近测试京东登陆cookie会话，有效时间挺长的，还是可以做长时间运行的。
> > 
> > 
> > cookie时间可以续期的，应该有接口，这种都可以慢慢优化，先把功能走通把
> 
> 续期活跃的已经都有了，先把这些bug跟功能优化了，后面能自动抢购的话，docker镜像还是很有用的，服务器部署

可以
